---
- name: join domain
  win_domain_membership:
   dns_domain_name: lab01.local
   hostname: appsql01
   domain_admin_user: "{{ win_domain_admin_user }}"
   domain_admin_password: "{{ win_domain_admin_password }}"
   state: domain
  register: domain_state

- name: reboot after domain join
  win_reboot:
  when: domain_state.reboot_required
