---
- gather_facts: no
  vars:
   #ansible_ssh_user: Administrator
   #ansible_ssh_pass: Welcome1
   #ansible_ssh_port: 5986
   #ansible_connection: winrm
   #ansible_winrm_server_cert_validation: ignore
   win_domain_admin_user: lab01\Administrator
   win_domain_admin_password: Welcome1  
  tasks:
  - name: join domain
    win_domain_membership:
      dns_domain_name: lab01.local
      hostname: appsql01
      domain_admin_user: "{{ win_domain_admin_user }}"
      domain_admin_password: "{{ win_domain_admin_password }}"
      state: domain
    register: domain_state

  - name: reboot after domain join
    win_reboot:
    when: domain_state.reboot_required
